#!/usr/bin/php
<?
set_include_path("../include");
require("header.inc.php");

require("../model/Error.inc.php");

if (empty($argv[1]) || empty($argv[2]) || empty($argv[3])) {
	die("Usage: $argv[0] " . 'groupname username role' . "\n");
}

$groupname = $argv[1];
$username = $argv[2];
$role = $argv[3];

$userID = Zotero_Users::getUserIDFromUsername($username);
if (!$userID) {
  die("User '$user' unknown\n");
}

if (($role != 'admin') && ($role != 'member')) {
  die("Role must be either 'admin' or 'member'.\n");
}

$sql = "SELECT groupID FROM groups WHERE name=?";
$groupID = Zotero_DB::valueQuery($sql, array($groupname));
if ($groupID === false) {
  die("Group '$groupname' unknown.\n");
}

$group = Zotero_Groups::get($groupID);

$currentrole = $group->getUserRole($userID);

if ($currentrole == $role) {
  echo "User '$username' is already $role of the group '$groupname'.\n";
  exit;
}

try {
  if ($currentrole === false) {
    $group->addUser($userID, $role);
    $msg = "Added user '$username' to group '$groupname'.\n";
  } else {
    $group->updateUser($userID, $role);
    $msg = "Changed user role from $currentrole to $role.\n";
  }

  $group->save();
} catch (Exception $e) {
  die($e->getMessage()."\n");
}

echo $msg;

?>